### ISSUE TITLE
代码示例有问题

### ISSUE THREAD

**Issue by tangxiaoqi-tangxiao** [nashaofu/xcap#106]
我把安装库后提示错误，没有xcap

代码：
use xcap::Monitor;

**Comment by nashaofu** [comment]
信息太少了

**Comment by tangxiaoqi-tangxiao** [comment]
![image](https://github.com/nashaofu/xcap/assets/54069236/b3f7b4b1-e3eb-44e5-b7cb-74166d837998)

**Comment by nashaofu** [comment]
你安装的是screenshots还是xcap？

**Comment by tangxiaoqi-tangxiao** [comment]
啊，不是一个东西吗，我就是看的screenshots项目地址，指向的就是这个项目啊

**Comment by tangxiaoqi-tangxiao** [comment]
而且你的示例完全可以不改的运行，除了引用包

**Comment by nashaofu** [comment]
xcap 是screenshots的升级版，需要修改一下包

**Comment by nashaofu** [comment]
嗯嗯，应该时文档有问题，我重新发布了版本，文档更新了
