### ISSUE TITLE
Error: "Get displays from point failed" on MacOS

### ISSUE THREAD

**Issue by tpatterson** [nashaofu/xcap#113]
This error happens to me when I plug in a second monitor, then arrange the displays so the second monitor appears to the left and above the primary monitor. See the image.

SECONDARY ISSUE: 
The whole request fails whenever there is an issue returning results for any window in ImplWindow::all(). 
Instead of failing when one window is unavailable, could xcap instead proceed to return valid results for the other windows that didn't fail? Perhaps by returning a `Vec<Option<Window>>`

<img width="602" alt="image" src="https://github.com/nashaofu/xcap/assets/1031531/68b8dd87-2062-404d-a950-1a7ed845eda4">

**Comment by tpatterson** [comment]
@nashaofu xcap is great, thank you for making it! I'd be willing to sponsor you more to clean up some bugs and panics.

**Comment by nashaofu** [comment]
> @nashaofu xcap is great, thank you for making it! I'd be willing to sponsor you more to clean up some bugs and panics.

Thank you very much for your sponsorship. I will try to fix it this week

**Comment by tpatterson** [comment]
> > @nashaofu xcap is great, thank you for making it! I'd be willing to sponsor you more to clean up some bugs and panics.
> 
> Thank you very much for your sponsorship. I will try to fix it this week

Thank you

**Comment by nashaofu** [comment]
I have fixed this issue, try upgrading to 0.0.6.

**Comment by tpatterson** [comment]
This also seems to have fixed another issue where the coordinates of windows in were outside the bounds of their monitor. I'll report if I see that issue pop up again. Great work.
