### ISSUE TITLE
Saving screenshot as JPEG only produces garbage

### ISSUE THREAD

**Issue by gucki** [nashaofu/xcap#114]
This works as expected:

        image
            .save(format!("monitor-{}.png", normalized(monitor.name())))
            .unwrap();

This produces a completely broken JPEG file:

        image
            .save(format!("monitor-{}.jpg", normalized(monitor.name())))
            .unwrap();

I'm crosscompiling from linux to windows using `cargo build --target x86_64-pc-windows-gnu`.

**Comment by nashaofu** [comment]
This should be a bug in crate image，https://github.com/image-rs/image/issues/2184
