### ISSUE TITLE
Macos screenshot gets background only 

### ISSUE THREAD

**Issue by itsmhe** [nashaofu/xcap#144]
Hi there,

im using your xcap in a tauri application and when i take a screenshot with this library of the whole screen i can only see the application itself and the desktop.

Even when i run the code from the readme.md file to get the screenshots, i only get the background with no applications on it.

I suspect this is some kind of privacy or permissions problem, but I do not know where to start.

**Comment by nashaofu** [comment]
https://github.com/nashaofu/xcap/issues/123

**Comment by nashaofu** [comment]
```rust
use core_graphics::access::ScreenCaptureAccess;
use sysinfo::System;

pub fn has_permission() -> bool {
    ScreenCaptureAccess::default().preflight()
}

pub fn request_permission() -> bool {
    ScreenCaptureAccess::default().request()
}
```

**Comment by itsmhe** [comment]
Code signing fixed it for me. Thanks for the help.
