### ISSUE TITLE
memory leak in `Windows:all()` on macos

### ISSUE THREAD

**Issue by louis030195** [nashaofu/xcap#148]
<img width="1396" alt="Screenshot 2024-08-24 at 17 21 33" src="https://github.com/user-attachments/assets/d9e392d5-e9a0-4c73-a853-027f522bd92d">

https://github.com/nashaofu/xcap/blob/daff24c6a50bf1fc38f6f9974ced71d8d48004c5/src/macos/impl_window.rs#L177

https://github.com/servo/core-foundation-rs/blob/b2fdaf4132a8fff7aadd6885ec7c570296a664ea/core-graphics/src/window.rs#L145
any idea how to fix?

i tried to release the object manually but got seg faults then

**Comment by louis030195** [comment]
https://github.com/louis030195/xcap/blob/75a7152b1990a182b16af67ae3db9d8916e0a734/src/macos/impl_window.rs#L262 added a test

**Comment by nashaofu** [comment]
fixed #149
