### ISSUE TITLE
由于1.77.2是支持WIN7的最后一个版本

### ISSUE THREAD

**Issue by enp6** [nashaofu/xcap#153]
目前使用最新的会提示这个
error: package `ravif v0.11.10` cannot be built because it requires rustc 1.79 or newer, while the currently active rustc version is 1.77.2

**Comment by chenjietao** [comment]
https://github.com/kornelski/cavif-rs/issues/82#issuecomment-2234635159

运行`cargo update --precise 0.11.6 -p ravif`之后再build

**Comment by lz520520** [comment]
cargo update image --precise 0.25.4
	cargo update ravif --precise 0.11.6

**Comment by nashaofu** [comment]
发布了0.0.15 可以支持win7，后续版本因为要是实现录屏功能，所以不会再支持win7了
