### ISSUE TITLE
Get the z-index of a window?

### ISSUE THREAD

**Issue by Mufanc** [nashaofu/xcap#175]
I am planning to develop a screenshot tool using Tauri, which includes the functionality to select a window for capturing. Users will be able to move the mouse cursor to select the window they wish to capture, similar to traditional screenshot tools such as [Snipaste](https://www.snipaste.com/). 

However, it appears that xcap currently [does not support retrieving the z-index of a window](https://docs.rs/xcap/latest/xcap/struct.Window.html#implementations). In other words, when a user moves the mouse cursor to a specific coordinate and there are multiple windows containing this coordinate, I am unable to determine which window to capture. 

Therefore, I would like to inquire politely to the developers whether there are any plans to add the capability to retrieve the z-index of windows in xcap in the future.

**Comment by nashaofu** [comment]
Merged https://github.com/nashaofu/xcap/pull/173
