### ISSUE TITLE
Incorrect scale_factor on Windows

### ISSUE THREAD

**Issue by caesay** [nashaofu/xcap#176]
If dpiAware is set in application manifest eg.

```
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">True</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </windowsSettings>
  </application>
```

Then xcap will return `scale_factor = 1.0` always, which is incorrect. The [GetDpiForMonitor](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/UI/HiDpi/fn.GetDpiForMonitor.html) function should be used to determine the monitor scale.

**Comment by nashaofu** [comment]
https://github.com/nashaofu/xcap/tree/dev
See if this meets your requirements, I have no actual testing, you can help adjust the parameters

features: https://learn.microsoft.com/zh-cn/windows/win32/api/shellscalingapi/ne-shellscalingapi-monitor_dpi_type
```
windows_hi_dpi_effective = ["windows/Win32_UI_HiDpi"]
windows_hi_dpi_angular = ["windows/Win32_UI_HiDpi"]
windows_hi_dpi_raw = ["windows/Win32_UI_HiDpi"]
```

**Comment by nashaofu** [comment]
@caesay Does this align with your expectations?

**Comment by caesay** [comment]
Hi, thanks for looking at this, and I think the changes you made will work fine for me, but the only valid mode is MDT_EFFECTIVE_DPI, so I'm not sure the cargo features are needed to gate this.

If I could provide a suggestion, ideally the implementation should just use `GetDpiForMonitor` automatically if Windows >= 8.1, since the current approach of `GetDeviceCaps` will give incorrect results on multi-monitor computers. If xcap is supporting older versions of windows than 8.1, then use `libloading` to access `GetDpiForMonitor` dynamically, instead of statically importing the function.

The current implementation in #177 means that I have to choose whether I target windows 7/8 or 8.1+ at compile time, since without the feature it will not work on 8.1+ and with the feature it will not work on 7.

**Comment by nashaofu** [comment]
The cargo features have been removed and replaced with dynamic linking. Additionally, it now detects whether the current process has DPI awareness enabled, and automatically switches the method for obtaining DPI accordingly.
```
use std::time::Instant;
use windows::Win32::UI::HiDpi::{
    SetProcessDpiAwareness, PROCESS_DPI_AWARENESS, PROCESS_PER_MONITOR_DPI_AWARE,
};
use xcap::Monitor;

fn change_windows_dpi_awarness(val: PROCESS_DPI_AWARENESS) {
    unsafe {
        SetProcessDpiAwareness(val).unwrap();
    }
}

fn main() {
    // Modify the program's DPI awareness. You can set the value to PROCESS_DPI_UNAWARE or PROCESS_PER_MONITOR_DPI_AWARE for testing.
    // 修改程序的 DPI 感知，你可以将值设置为 PROCESS_DPI_UNAWARE 或 PROCESS_PER_MONITOR_DPI_AWARE 进行测试
    change_windows_dpi_awarness(PROCESS_PER_MONITOR_DPI_AWARE);
    let start = Instant::now();
    let monitors = Monitor::all().unwrap();
    println!("Monitor::all() 运行耗时: {:?}", start.elapsed());

    for monitor in monitors {
        println!(
            "Monitor:\n id: {}\n name: {}\n position: {:?}\n size: {:?}\n state:{:?}\n",
            monitor.id(),
            monitor.name(),
            (monitor.x(), monitor.y()),
            (monitor.width(), monitor.height()),
            (
                monitor.rotation(),
                monitor.scale_factor(),
                monitor.frequency(),
                monitor.is_primary()
            )
        );
    }

    let monitor = Monitor::from_point(100, 100).unwrap();

    println!("Monitor::from_point(): {}", monitor.name());
    println!(
        "Monitor::from_point(100, 100) 运行耗时: {:?}",
        start.elapsed()
    );

    println!("运行耗时: {:?}", start.elapsed());
}

```

**Comment by nashaofu** [comment]
Released https://github.com/nashaofu/xcap/releases/tag/v0.1.1

**Comment by nashaofu** [comment]
I have closed this question for now. If there are any issues, please reopen it
