### ISSUE TITLE
scale_factor 值获取有误

### ISSUE THREAD

**Issue by lopo12123** [nashaofu/xcap#52]
以下是我的电脑的设置
![image](https://github.com/nashaofu/screenshots-rs/assets/59609929/8a8357b4-af5e-40a2-9464-d058b70789e0)

我发现我用这个库获取屏幕列表信息的时候的 `scale_factor` 仍然是 `1`.

以下是我使用 fltk-rs 和 此库 分别获取屏幕 `xywh` 和 `scale_factor` 的值的测试代码和对应输出
![image](https://github.com/nashaofu/screenshots-rs/assets/59609929/74ea656d-ecd9-4c23-8b2f-6a1324f1ebba)
![image](https://github.com/nashaofu/screenshots-rs/assets/59609929/5cc00c1d-38f8-45d4-bbc6-1563e0d4a387)

**Comment by nashaofu** [comment]
我这个是和electron的对齐的

**Comment by Originalimoc** [comment]
确认这个bug，再加上3840x2160 w/150%缩放会出现已经获取了display_info: 2560x1440 + 0.6666 scale_factor，再加上fn capture_screen_area里面还乘了一次，然后就获得了原分辨率÷1.5*0.666的一张1706x960的左上角50%不到的局部截图。。。

**Comment by nashaofu** [comment]
> 确认这个bug，再加上3840x2160 w/150%缩放会出现已经获取了display_info: 2560x1440 + 0.6666 scale_factor，再加上fn capture_screen_area里面还乘了一次，然后就获得了原分辨率÷1.5*0.666的一张1706x960的左上角50%不到的局部截图。。。

这一一个错误，我已经在display-info中修复，更新一下lock文件即可

**Comment by Originalimoc** [comment]
Mine seems to be fine? 4K screen, but I'm on Win11 though. "Screen { display_info: DisplayInfo { id: 2776250164, raw_handle: HMONITOR(161683325), x: 0, y: 0, width: 3072, height: 1728, rotation: 0.0, scale_factor: 1.25, frequency: 60.0, is_primary: true } }"

**Comment by nashaofu** [comment]
https://github.com/nashaofu/xcap/issues/176#issuecomment-2558136796，再win8后，设置一下进程dpi感知，可以获取准确的缩放比例
