### ISSUE TITLE
能截取指定窗口吗？

### ISSUE THREAD

**Issue by mztlive** [nashaofu/xcap#53]
我正在用tauri开发一个多窗口的程序，正在找一个能解决指定窗口内可见内容的截图包，不知道你这个行不行。 如果有什么方法可以解决这个问题，不胜感激。

**Comment by bigduu** [comment]
MacOS 吗?

**Comment by nashaofu** [comment]
目前不支持，需要开发

**Comment by nashaofu** [comment]
已经支持，安装xcap crate
