### ISSUE TITLE
windows上使用在service中使用system权限截屏报错

### ISSUE THREAD

**Issue by RickSKy** [nashaofu/xcap#61]
调用screen.capture() 错误信息为：拒绝访问 , 0x80070005；

**Comment by ihsanrabb** [comment]
I have same issue in windows 11. any update how to fix this?

**Comment by nashaofu** [comment]
能给一个示例代码吗？我不是很了解windows开发

**Comment by mikey0000** [comment]
Was looking through the windows code and your supposed to wrap GDI calls in GdiplusStartup and GdiplusShutdown at least in C++ code.

**Comment by RickSKy** [comment]
The session of a Windows system user does not have a desktop station, therefore it is not possible to take screenshots.
