### ISSUE TITLE
2008上截图是空白的

### ISSUE THREAD

**Issue by lz520520** [nashaofu/xcap#92]
如下所示，
![image](https://github.com/nashaofu/xcap/assets/30519218/0ccc926f-850a-452f-af2d-5aa8d575baff)

使用的参考代码是
```rust
use xcap::Monitor;
use std::time::Instant;

fn normalized(filename: &str) -> String {
    filename
        .replace("|", "")
        .replace("\\", "")
        .replace(":", "")
        .replace("/", "")
}

fn main() {
    let start = Instant::now();
    let monitors = Monitor::all().unwrap();

    for monitor in monitors {
        let image = monitor.capture_image().unwrap();

        image
            .save(format!("target/monitor-{}.png", normalized(monitor.name())))
            .unwrap();
    }

    println!("运行耗时: {:?}", start.elapsed());
}
```

**Comment by lz520520** [comment]
还遇到一个问题，我多屏幕的时候，两个屏幕分辨率不同，这个低分辨率的副屏截图会多出来一块主屏的图
![image](https://github.com/nashaofu/xcap/assets/30519218/61fa3529-fb52-4b08-94b0-5651f2ae035b)

**Comment by nashaofu** [comment]
windows 2008 的server吗？这个没有支持的打算哈

**Comment by nashaofu** [comment]
> 还遇到一个问题，我多屏幕的时候，两个屏幕分辨率不同，这个低分辨率的副屏截图会多出来一块主屏的图 ![image](https://private-user-images.githubusercontent.com/30519218/299581413-61fa3529-fb52-4b08-94b0-5651f2ae035b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODAzNzAsIm5iZiI6MTcwNjE4MDA3MCwicGF0aCI6Ii8zMDUxOTIxOC8yOTk1ODE0MTMtNjFmYTM1MjktZmI1Mi00YjA4LTk0YjAtNTY1MWYyYWUwMzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEwNTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZDVlZjhiMWViNzI5NGQ5Y2UwYzQwMTM4MGQzZGIzZmFlNjEwNTk4ZTgzYTczOWE1OGYwMGM4NzliMGRlYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQZPB3K5rxMXPE1rNGcwU2lJcI51oYxgwB4jI0Mm-B0)

这个晚点看一下

**Comment by lz520520** [comment]
我测试了一个golang的库，和你这个项目调用的差不多的接口，他在2008 server上是正常的。
https://github.com/kbinani/screenshot/blob/master/screenshot_windows.go

第二个问题我解决了，你可以参考下，主要是把capture_monitor函数中的monitor句柄换成当前桌面窗口句柄
https://github.com/lz520520/xcap

**Comment by lz520520** [comment]
我08換了台又截了一张，感觉是RGBA颜色问题
![image](https://github.com/nashaofu/xcap/assets/30519218/91d8c3ad-8da0-488c-a7aa-230a9a58b5c9)

**Comment by lz520520** [comment]
emmm，问题解决了，应该是2008不支持A
![image](https://github.com/nashaofu/xcap/assets/30519218/1c854c6c-3a27-4cb0-950e-1f0b0f2806b8)

**Comment by nashaofu** [comment]
> 还遇到一个问题，我多屏幕的时候，两个屏幕分辨率不同，这个低分辨率的副屏截图会多出来一块主屏的图 ![image](https://private-user-images.githubusercontent.com/30519218/299581413-61fa3529-fb52-4b08-94b0-5651f2ae035b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTI0NDcsIm5iZiI6MTcwNjE5MjE0NywicGF0aCI6Ii8zMDUxOTIxOC8yOTk1ODE0MTMtNjFmYTM1MjktZmI1Mi00YjA4LTk0YjAtNTY1MWYyYWUwMzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE0MTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmNThkNzc3MTJjMTQyZDA3M2Q4ZjdmYTZlNTE3NzYzYTU3OTQ5NGIzZmRjNTFlMGJlZjUzZjE2M2Q2NGIzMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-MlW4qNgfC7_TaMPxGkUCXmjeXdiBWgFb49ugy_Mpo)

你的分辨率是怎么设置的，我在自己电脑上复现一下

**Comment by lz520520** [comment]
主屏3840_2160，副屏1920_1080

**Comment by nashaofu** [comment]
你可以在你电脑上测试一下这个版本，https://github.com/nashaofu/xcap/pull/94

**Comment by lz520520** [comment]
测了ok了，就是CreateDC对应DeleteDC，GetDC/GetWindowDC对应ReleaseDC，还是有区别的
